/**
 * Alkor B2B product data access module.
 * Reads from data/products.json (generated by scrape-alkor.mjs).
 * Suitable for build-time / SSG usage.
 */

export interface AlkorProduct {
  sku: string;
  name: string;
  slug: string;
  description: string;
  price: string;
  priceDetail: string;
  category: string;
  specs: Record<string, string>;
  labels: string[];
  imagesHD: string[];
  localImages: string[];
  sourceUrl?: string;
  lastSync: string;
}

export interface AlkorProductSlim {
  sku: string;
  name: string;
  slug: string;
  price: string;
  description: string;
  image: string | null;
  imageCount: number;
}

export interface AlkorProductStats {
  totalProducts: number;
  categories: string[];
  lastSync: string | null;
}

let _cache: AlkorProduct[] | null = null;

function loadProducts(): AlkorProduct[] {
  if (_cache) return _cache;
  try {
    // Dynamic import for build-time usage — the JSON is generated by the scraper
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    _cache = require("../../data/products.json") as AlkorProduct[];
  } catch {
    _cache = [];
  }
  return _cache;
}

/**
 * Returns all scraped Alkor products.
 */
export function getAllProducts(): AlkorProduct[] {
  return loadProducts();
}

/**
 * Find a product by its SKU (Alkor reference).
 */
export function getProductBySKU(sku: string): AlkorProduct | undefined {
  return loadProducts().find((p) => p.sku === sku);
}

/**
 * Find a product by its slug.
 */
export function getProductBySlug(slug: string): AlkorProduct | undefined {
  return loadProducts().find((p) => p.slug === slug);
}

/**
 * Search products by name or description (case-insensitive).
 */
export function searchProducts(query: string): AlkorProduct[] {
  const q = query.toLowerCase().trim();
  if (!q) return [];
  const terms = q.split(/\s+/);
  return loadProducts().filter((p) => {
    const text = `${p.name} ${p.description} ${p.sku}`.toLowerCase();
    return terms.every((t) => text.includes(t));
  });
}

/**
 * Filter products by category.
 */
export function getProductsByCategory(category: string): AlkorProduct[] {
  const cat = category.toLowerCase().trim();
  return loadProducts().filter(
    (p) => p.category.toLowerCase().includes(cat)
  );
}

/**
 * Get catalog statistics.
 */
export function getProductStats(): AlkorProductStats {
  const products = loadProducts();
  const categories = [
    ...new Set(products.map((p) => p.category).filter(Boolean)),
  ].sort();
  const lastSync = products.reduce<string | null>((latest, p) => {
    if (!latest || p.lastSync > latest) return p.lastSync;
    return latest;
  }, null);

  return {
    totalProducts: products.length,
    categories,
    lastSync,
  };
}
