import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useCart } from '@/contexts/CartContext';
import { toast } from 'sonner';

export interface ReorderTemplate {
  id: string;
  account_id: string;
  name: string;
  description: string | null;
  is_auto_generated: boolean;
  created_by: string | null;
  last_used_at: string | null;
  created_at: string;
  updated_at: string;
  items?: ReorderTemplateItem[];
}

export interface ReorderTemplateItem {
  id: string;
  template_id: string;
  product_id: string | null;
  product_name: string;
  quantity: number;
  sort_order: number;
  created_at: string;
  products?: {
    price_ttc: number | null;
    price: number;
    image_url: string | null;
    category: string;
    stock_quantity: number | null;
  } | null;
}

export function useB2BReorderTemplates(accountId: string | undefined) {
  return useQuery({
    queryKey: ['b2b-templates', accountId],
    enabled: !!accountId,
    queryFn: async () => {
      const { data, error } = await supabase
        .from('b2b_reorder_templates')
        .select(`
          *,
          items:b2b_reorder_template_items(
            *,
            products(price, price_ttc, image_url, category, stock_quantity)
          )
        `)
        .eq('account_id', accountId!)
        .order('is_auto_generated', { ascending: false })
        .order('name');
      if (error) throw error;
      return data as ReorderTemplate[];
    },
  });
}

// Produits les plus commandés dans les 90 derniers jours (pour suggestions)
export function useB2BTopProducts(accountId: string | undefined) {
  return useQuery({
    queryKey: ['b2b-top-products', accountId],
    enabled: !!accountId,
    queryFn: async () => {
      const since = new Date();
      since.setDate(since.getDate() - 90);

      // Récupère les order_items des commandes des membres de ce compte
      const { data: members } = await supabase
        .from('b2b_company_users')
        .select('user_id')
        .eq('account_id', accountId!);

      const memberIds = (members ?? []).map(m => m.user_id);
      if (memberIds.length === 0) return [];

      const { data: orders } = await supabase
        .from('orders')
        .select('id')
        .in('user_id', memberIds)
        .gte('created_at', since.toISOString());

      const orderIds = (orders ?? []).map(o => o.id);
      if (orderIds.length === 0) return [];

      const { data: items, error } = await supabase
        .from('order_items')
        .select('product_id, product_name, quantity')
        .in('order_id', orderIds);

      if (error) throw error;

      // Agrégation côté client
      const agg: Record<string, { product_id: string; product_name: string; total_qty: number }> = {};
      for (const item of items ?? []) {
        if (!item.product_id) continue;
        if (!agg[item.product_id]) {
          agg[item.product_id] = { product_id: item.product_id, product_name: item.product_name, total_qty: 0 };
        }
        agg[item.product_id].total_qty += item.quantity;
      }

      return Object.values(agg)
        .sort((a, b) => b.total_qty - a.total_qty)
        .slice(0, 20);
    },
  });
}

export function useB2BReorderTemplateMutations() {
  const qc = useQueryClient();
  const { addToCart } = useCart();

  const createTemplate = useMutation({
    mutationFn: async ({
      accountId,
      name,
      description,
      items,
      isAutoGenerated,
      createdBy,
    }: {
      accountId: string;
      name: string;
      description?: string;
      items: { product_id: string; product_name: string; quantity: number }[];
      isAutoGenerated?: boolean;
      createdBy?: string;
    }) => {
      const { data: template, error: tErr } = await supabase
        .from('b2b_reorder_templates')
        .insert({
          account_id: accountId,
          name,
          description: description || null,
          is_auto_generated: isAutoGenerated ?? false,
          created_by: createdBy || null,
        })
        .select('id')
        .single();
      if (tErr) throw tErr;

      if (items.length > 0) {
        const { error: iErr } = await supabase
          .from('b2b_reorder_template_items')
          .insert(items.map((item, idx) => ({
            template_id: template.id,
            product_id: item.product_id,
            product_name: item.product_name,
            quantity: item.quantity,
            sort_order: idx,
          })));
        if (iErr) throw iErr;
      }

      return template;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['b2b-templates'] });
      toast.success('Template créé');
    },
    onError: (e: any) => toast.error(`Erreur : ${e.message}`),
  });

  const deleteTemplate = useMutation({
    mutationFn: async (templateId: string) => {
      const { error } = await supabase
        .from('b2b_reorder_templates')
        .delete()
        .eq('id', templateId);
      if (error) throw error;
    },
    onSuccess: () => {
      qc.invalidateQueries({ queryKey: ['b2b-templates'] });
      toast.success('Template supprimé');
    },
  });

  // Ajouter tous les items d'un template au panier
  const orderFromTemplate = async (template: ReorderTemplate) => {
    if (!template.items || template.items.length === 0) {
      toast.error('Ce template est vide');
      return;
    }

    let added = 0;
    for (const item of template.items) {
      if (!item.product_id) continue;
      const price = item.products?.price_ttc ?? item.products?.price ?? 0;
      for (let i = 0; i < item.quantity; i++) {
        addToCart({
          id: item.product_id,
          name: item.product_name,
          price: price.toFixed(2),
          image: item.products?.image_url || '/placeholder.svg',
          category: item.products?.category || '',
          stock_quantity: item.products?.stock_quantity ?? 9999,
        });
      }
      added++;
    }

    // Mettre à jour last_used_at
    await supabase
      .from('b2b_reorder_templates')
      .update({ last_used_at: new Date().toISOString() })
      .eq('id', template.id);

    qc.invalidateQueries({ queryKey: ['b2b-templates'] });
    toast.success(`${added} produit${added > 1 ? 's' : ''} ajouté${added > 1 ? 's' : ''} au panier`);
  };

  return { createTemplate, deleteTemplate, orderFromTemplate };
}
