#!/usr/bin/env python3
"""
Données de référence — listes scolaires par niveau
14 niveaux : PS → Terminale
"""

SCHOOL_LISTS = {
    "PS": {
        "level": "Petite Section",
        "cycle": "Maternelle",
        "items": [
            {"name": "Boîte de crayons de couleur (12)", "qty": 1, "category": "Coloriage"},
            {"name": "Boîte de feutres lavables (12)", "qty": 1, "category": "Coloriage"},
            {"name": "Tablier de peinture", "qty": 1, "category": "Arts plastiques"},
            {"name": "Paire de ciseaux bouts ronds", "qty": 1, "category": "Découpage"},
            {"name": "Bâton de colle 8g", "qty": 2, "category": "Collage"},
            {"name": "Pochette de papier dessin A4", "qty": 1, "category": "Papier"},
            {"name": "Cahier de dessin 24x32", "qty": 1, "category": "Cahier"},
            {"name": "Boîte de mouchoirs", "qty": 2, "category": "Hygiène"},
        ]
    },
    "MS": {
        "level": "Moyenne Section",
        "cycle": "Maternelle",
        "items": [
            {"name": "Boîte de crayons de couleur (12)", "qty": 1, "category": "Coloriage"},
            {"name": "Boîte de feutres lavables (12)", "qty": 1, "category": "Coloriage"},
            {"name": "Tablier de peinture", "qty": 1, "category": "Arts plastiques"},
            {"name": "Paire de ciseaux bouts ronds", "qty": 1, "category": "Découpage"},
            {"name": "Bâton de colle 8g", "qty": 3, "category": "Collage"},
            {"name": "Pochette de papier dessin A4", "qty": 1, "category": "Papier"},
            {"name": "Cahier de dessin 24x32", "qty": 1, "category": "Cahier"},
            {"name": "Crayon graphite HB", "qty": 2, "category": "Écriture"},
            {"name": "Gomme blanche", "qty": 1, "category": "Écriture"},
            {"name": "Boîte de mouchoirs", "qty": 2, "category": "Hygiène"},
        ]
    },
    "GS": {
        "level": "Grande Section",
        "cycle": "Maternelle",
        "items": [
            {"name": "Boîte de crayons de couleur (12)", "qty": 1, "category": "Coloriage"},
            {"name": "Boîte de feutres lavables (12)", "qty": 1, "category": "Coloriage"},
            {"name": "Paire de ciseaux bouts ronds", "qty": 1, "category": "Découpage"},
            {"name": "Bâton de colle 8g", "qty": 4, "category": "Collage"},
            {"name": "Pochette de papier dessin A4", "qty": 1, "category": "Papier"},
            {"name": "Cahier 17x22 48 pages seyes 4mm", "qty": 2, "category": "Cahier"},
            {"name": "Crayon graphite HB", "qty": 2, "category": "Écriture"},
            {"name": "Gomme blanche", "qty": 1, "category": "Écriture"},
            {"name": "Taille-crayon avec réservoir", "qty": 1, "category": "Écriture"},
            {"name": "Ardoise blanche + feutre effaçable", "qty": 1, "category": "Écriture"},
            {"name": "Boîte de mouchoirs", "qty": 2, "category": "Hygiène"},
        ]
    },
    "CP": {
        "level": "CP",
        "cycle": "Cycle 2",
        "items": [
            {"name": "Cartable 38cm", "qty": 1, "category": "Maroquinerie"},
            {"name": "Trousse", "qty": 1, "category": "Maroquinerie"},
            {"name": "Crayon graphite HB", "qty": 4, "category": "Écriture"},
            {"name": "Gomme blanche", "qty": 2, "category": "Écriture"},
            {"name": "Taille-crayon avec réservoir", "qty": 1, "category": "Écriture"},
            {"name": "Règle plate 30cm transparente", "qty": 1, "category": "Traçage"},
            {"name": "Boîte de crayons de couleur (12)", "qty": 1, "category": "Coloriage"},
            {"name": "Boîte de feutres (12)", "qty": 1, "category": "Coloriage"},
            {"name": "Paire de ciseaux bouts ronds", "qty": 1, "category": "Découpage"},
            {"name": "Bâton de colle 8g", "qty": 4, "category": "Collage"},
            {"name": "Cahier 17x22 48 pages seyes", "qty": 5, "category": "Cahier"},
            {"name": "Protège-cahier 17x22", "qty": 5, "category": "Cahier"},
            {"name": "Ardoise blanche + feutre effaçable", "qty": 1, "category": "Écriture"},
            {"name": "Pochette de papier dessin A4", "qty": 1, "category": "Papier"},
        ]
    },
    "CE1": {
        "level": "CE1",
        "cycle": "Cycle 2",
        "items": [
            {"name": "Cartable 38cm", "qty": 1, "category": "Maroquinerie"},
            {"name": "Trousse", "qty": 1, "category": "Maroquinerie"},
            {"name": "Crayon graphite HB", "qty": 4, "category": "Écriture"},
            {"name": "Stylo bille bleu", "qty": 2, "category": "Écriture"},
            {"name": "Stylo bille rouge", "qty": 1, "category": "Écriture"},
            {"name": "Stylo bille vert", "qty": 1, "category": "Écriture"},
            {"name": "Gomme blanche", "qty": 2, "category": "Écriture"},
            {"name": "Taille-crayon avec réservoir", "qty": 1, "category": "Écriture"},
            {"name": "Règle plate 30cm transparente", "qty": 1, "category": "Traçage"},
            {"name": "Boîte de crayons de couleur (12)", "qty": 1, "category": "Coloriage"},
            {"name": "Boîte de feutres (12)", "qty": 1, "category": "Coloriage"},
            {"name": "Paire de ciseaux bouts ronds", "qty": 1, "category": "Découpage"},
            {"name": "Bâton de colle 8g", "qty": 4, "category": "Collage"},
            {"name": "Cahier 17x22 48 pages seyes", "qty": 5, "category": "Cahier"},
            {"name": "Protège-cahier 17x22", "qty": 5, "category": "Cahier"},
            {"name": "Cahier de brouillon 17x22", "qty": 1, "category": "Cahier"},
        ]
    },
    "CE2": {
        "level": "CE2",
        "cycle": "Cycle 2",
        "items": [
            {"name": "Cartable ou sac à dos", "qty": 1, "category": "Maroquinerie"},
            {"name": "Trousse", "qty": 1, "category": "Maroquinerie"},
            {"name": "Crayon graphite HB", "qty": 4, "category": "Écriture"},
            {"name": "Stylo bille 4 couleurs", "qty": 1, "category": "Écriture"},
            {"name": "Stylo plume + cartouches bleues", "qty": 1, "category": "Écriture"},
            {"name": "Effaceur", "qty": 1, "category": "Écriture"},
            {"name": "Gomme blanche", "qty": 2, "category": "Écriture"},
            {"name": "Taille-crayon avec réservoir", "qty": 1, "category": "Écriture"},
            {"name": "Règle plate 30cm transparente", "qty": 1, "category": "Traçage"},
            {"name": "Équerre 60°", "qty": 1, "category": "Traçage"},
            {"name": "Boîte de crayons de couleur (12)", "qty": 1, "category": "Coloriage"},
            {"name": "Boîte de feutres (12)", "qty": 1, "category": "Coloriage"},
            {"name": "Paire de ciseaux bouts ronds", "qty": 1, "category": "Découpage"},
            {"name": "Bâton de colle 8g", "qty": 4, "category": "Collage"},
            {"name": "Cahier 24x32 96 pages seyes", "qty": 4, "category": "Cahier"},
            {"name": "Protège-cahier 24x32", "qty": 4, "category": "Cahier"},
            {"name": "Cahier de brouillon", "qty": 1, "category": "Cahier"},
        ]
    },
    "CM1": {
        "level": "CM1",
        "cycle": "Cycle 3",
        "items": [
            {"name": "Cartable ou sac à dos", "qty": 1, "category": "Maroquinerie"},
            {"name": "Trousse", "qty": 1, "category": "Maroquinerie"},
            {"name": "Agenda ou cahier de textes", "qty": 1, "category": "Organisation"},
            {"name": "Crayon graphite HB", "qty": 4, "category": "Écriture"},
            {"name": "Stylo plume + cartouches bleues", "qty": 1, "category": "Écriture"},
            {"name": "Stylo bille 4 couleurs", "qty": 1, "category": "Écriture"},
            {"name": "Effaceur + réécriveur", "qty": 1, "category": "Écriture"},
            {"name": "Surligneur (lot de 4)", "qty": 1, "category": "Écriture"},
            {"name": "Gomme blanche", "qty": 2, "category": "Écriture"},
            {"name": "Taille-crayon avec réservoir", "qty": 1, "category": "Écriture"},
            {"name": "Règle plate 30cm transparente", "qty": 1, "category": "Traçage"},
            {"name": "Équerre 60°", "qty": 1, "category": "Traçage"},
            {"name": "Compas", "qty": 1, "category": "Traçage"},
            {"name": "Boîte de crayons de couleur (12)", "qty": 1, "category": "Coloriage"},
            {"name": "Boîte de feutres (12)", "qty": 1, "category": "Coloriage"},
            {"name": "Paire de ciseaux", "qty": 1, "category": "Découpage"},
            {"name": "Bâton de colle 8g", "qty": 4, "category": "Collage"},
            {"name": "Cahier 24x32 96 pages seyes", "qty": 5, "category": "Cahier"},
            {"name": "Protège-cahier 24x32", "qty": 5, "category": "Cahier"},
            {"name": "Classeur A4 4 anneaux", "qty": 1, "category": "Classement"},
            {"name": "Lot de feuilles simples A4 seyes", "qty": 1, "category": "Papier"},
        ]
    },
    "CM2": {
        "level": "CM2",
        "cycle": "Cycle 3",
        "items": [
            {"name": "Cartable ou sac à dos", "qty": 1, "category": "Maroquinerie"},
            {"name": "Trousse", "qty": 1, "category": "Maroquinerie"},
            {"name": "Agenda", "qty": 1, "category": "Organisation"},
            {"name": "Crayon graphite HB", "qty": 4, "category": "Écriture"},
            {"name": "Stylo plume + cartouches bleues", "qty": 1, "category": "Écriture"},
            {"name": "Stylo bille 4 couleurs", "qty": 1, "category": "Écriture"},
            {"name": "Effaceur + réécriveur", "qty": 1, "category": "Écriture"},
            {"name": "Surligneur (lot de 4)", "qty": 1, "category": "Écriture"},
            {"name": "Gomme blanche", "qty": 2, "category": "Écriture"},
            {"name": "Taille-crayon avec réservoir", "qty": 1, "category": "Écriture"},
            {"name": "Règle plate 30cm transparente", "qty": 1, "category": "Traçage"},
            {"name": "Équerre 60°", "qty": 1, "category": "Traçage"},
            {"name": "Compas", "qty": 1, "category": "Traçage"},
            {"name": "Rapporteur", "qty": 1, "category": "Traçage"},
            {"name": "Boîte de crayons de couleur (12)", "qty": 1, "category": "Coloriage"},
            {"name": "Boîte de feutres (12)", "qty": 1, "category": "Coloriage"},
            {"name": "Paire de ciseaux", "qty": 1, "category": "Découpage"},
            {"name": "Bâton de colle 8g", "qty": 4, "category": "Collage"},
            {"name": "Cahier 24x32 96 pages seyes", "qty": 5, "category": "Cahier"},
            {"name": "Protège-cahier 24x32", "qty": 5, "category": "Cahier"},
            {"name": "Classeur A4 4 anneaux", "qty": 1, "category": "Classement"},
            {"name": "Lot de feuilles simples A4 seyes", "qty": 1, "category": "Papier"},
            {"name": "Calculatrice primaire", "qty": 1, "category": "Calcul"},
        ]
    },
    "6eme": {
        "level": "6ème",
        "cycle": "Cycle 3",
        "items": [
            {"name": "Sac à dos collège", "qty": 1, "category": "Maroquinerie"},
            {"name": "Trousse", "qty": 1, "category": "Maroquinerie"},
            {"name": "Agenda", "qty": 1, "category": "Organisation"},
            {"name": "Stylo plume + cartouches bleues", "qty": 1, "category": "Écriture"},
            {"name": "Stylo bille bleu, noir, rouge, vert", "qty": 4, "category": "Écriture"},
            {"name": "Crayon graphite HB", "qty": 4, "category": "Écriture"},
            {"name": "Porte-mine 0.5mm + mines", "qty": 1, "category": "Écriture"},
            {"name": "Surligneur (lot de 4)", "qty": 1, "category": "Écriture"},
            {"name": "Effaceur + réécriveur", "qty": 2, "category": "Écriture"},
            {"name": "Gomme blanche", "qty": 2, "category": "Écriture"},
            {"name": "Taille-crayon avec réservoir", "qty": 1, "category": "Écriture"},
            {"name": "Correcteur (souris ou stylo)", "qty": 1, "category": "Écriture"},
            {"name": "Règle plate 30cm", "qty": 1, "category": "Traçage"},
            {"name": "Équerre 60°", "qty": 1, "category": "Traçage"},
            {"name": "Compas", "qty": 1, "category": "Traçage"},
            {"name": "Rapporteur", "qty": 1, "category": "Traçage"},
            {"name": "Boîte de crayons de couleur (12)", "qty": 1, "category": "Coloriage"},
            {"name": "Boîte de feutres (12)", "qty": 1, "category": "Coloriage"},
            {"name": "Paire de ciseaux", "qty": 1, "category": "Découpage"},
            {"name": "Bâton de colle 21g", "qty": 2, "category": "Collage"},
            {"name": "Cahier 24x32 96 pages grands carreaux", "qty": 6, "category": "Cahier"},
            {"name": "Protège-cahier 24x32", "qty": 6, "category": "Cahier"},
            {"name": "Cahier 24x32 96 pages petits carreaux", "qty": 2, "category": "Cahier"},
            {"name": "Classeur A4 4 anneaux", "qty": 2, "category": "Classement"},
            {"name": "Lot de feuilles simples A4 grands carreaux", "qty": 2, "category": "Papier"},
            {"name": "Lot de feuilles doubles A4 grands carreaux", "qty": 1, "category": "Papier"},
            {"name": "Intercalaires 6 positions", "qty": 2, "category": "Classement"},
            {"name": "Pochettes plastiques perforées (lot 50)", "qty": 1, "category": "Classement"},
            {"name": "Calculatrice collège", "qty": 1, "category": "Calcul"},
        ]
    },
    "5eme": {
        "level": "5ème",
        "cycle": "Cycle 4",
        "items": [
            {"name": "Sac à dos collège", "qty": 1, "category": "Maroquinerie"},
            {"name": "Trousse", "qty": 1, "category": "Maroquinerie"},
            {"name": "Agenda", "qty": 1, "category": "Organisation"},
            {"name": "Stylo plume + cartouches bleues", "qty": 1, "category": "Écriture"},
            {"name": "Stylo bille bleu, noir, rouge, vert", "qty": 4, "category": "Écriture"},
            {"name": "Crayon graphite HB", "qty": 4, "category": "Écriture"},
            {"name": "Porte-mine 0.5mm + mines", "qty": 1, "category": "Écriture"},
            {"name": "Surligneur (lot de 4)", "qty": 1, "category": "Écriture"},
            {"name": "Effaceur + réécriveur", "qty": 2, "category": "Écriture"},
            {"name": "Gomme blanche", "qty": 2, "category": "Écriture"},
            {"name": "Correcteur (souris ou stylo)", "qty": 1, "category": "Écriture"},
            {"name": "Règle plate 30cm", "qty": 1, "category": "Traçage"},
            {"name": "Équerre 60°", "qty": 1, "category": "Traçage"},
            {"name": "Compas", "qty": 1, "category": "Traçage"},
            {"name": "Rapporteur", "qty": 1, "category": "Traçage"},
            {"name": "Boîte de crayons de couleur (12)", "qty": 1, "category": "Coloriage"},
            {"name": "Paire de ciseaux", "qty": 1, "category": "Découpage"},
            {"name": "Bâton de colle 21g", "qty": 2, "category": "Collage"},
            {"name": "Cahier 24x32 96 pages grands carreaux", "qty": 6, "category": "Cahier"},
            {"name": "Protège-cahier 24x32", "qty": 6, "category": "Cahier"},
            {"name": "Cahier 24x32 96 pages petits carreaux", "qty": 2, "category": "Cahier"},
            {"name": "Classeur A4 4 anneaux", "qty": 2, "category": "Classement"},
            {"name": "Lot de feuilles simples A4 grands carreaux", "qty": 2, "category": "Papier"},
            {"name": "Lot de feuilles doubles A4 grands carreaux", "qty": 1, "category": "Papier"},
            {"name": "Calculatrice collège scientifique", "qty": 1, "category": "Calcul"},
        ]
    },
    "4eme": {
        "level": "4ème",
        "cycle": "Cycle 4",
        "items": [
            {"name": "Sac à dos collège", "qty": 1, "category": "Maroquinerie"},
            {"name": "Trousse", "qty": 1, "category": "Maroquinerie"},
            {"name": "Agenda", "qty": 1, "category": "Organisation"},
            {"name": "Stylo bille bleu, noir, rouge, vert", "qty": 4, "category": "Écriture"},
            {"name": "Crayon graphite HB", "qty": 2, "category": "Écriture"},
            {"name": "Porte-mine 0.5mm + mines", "qty": 1, "category": "Écriture"},
            {"name": "Surligneur (lot de 4)", "qty": 1, "category": "Écriture"},
            {"name": "Correcteur (souris ou stylo)", "qty": 1, "category": "Écriture"},
            {"name": "Gomme blanche", "qty": 1, "category": "Écriture"},
            {"name": "Règle plate 30cm", "qty": 1, "category": "Traçage"},
            {"name": "Équerre 60°", "qty": 1, "category": "Traçage"},
            {"name": "Compas", "qty": 1, "category": "Traçage"},
            {"name": "Rapporteur", "qty": 1, "category": "Traçage"},
            {"name": "Boîte de crayons de couleur (12)", "qty": 1, "category": "Coloriage"},
            {"name": "Paire de ciseaux", "qty": 1, "category": "Découpage"},
            {"name": "Bâton de colle 21g", "qty": 2, "category": "Collage"},
            {"name": "Cahier 24x32 96 pages grands carreaux", "qty": 5, "category": "Cahier"},
            {"name": "Cahier 24x32 96 pages petits carreaux", "qty": 2, "category": "Cahier"},
            {"name": "Classeur A4 4 anneaux", "qty": 2, "category": "Classement"},
            {"name": "Lot de feuilles simples A4 grands carreaux", "qty": 2, "category": "Papier"},
            {"name": "Lot de feuilles doubles A4 grands carreaux", "qty": 1, "category": "Papier"},
            {"name": "Calculatrice collège scientifique", "qty": 1, "category": "Calcul"},
            {"name": "Clé USB 16Go", "qty": 1, "category": "Numérique"},
        ]
    },
    "3eme": {
        "level": "3ème",
        "cycle": "Cycle 4",
        "items": [
            {"name": "Sac à dos collège", "qty": 1, "category": "Maroquinerie"},
            {"name": "Trousse", "qty": 1, "category": "Maroquinerie"},
            {"name": "Agenda", "qty": 1, "category": "Organisation"},
            {"name": "Stylo bille bleu, noir, rouge, vert", "qty": 4, "category": "Écriture"},
            {"name": "Crayon graphite HB", "qty": 2, "category": "Écriture"},
            {"name": "Porte-mine 0.5mm + mines", "qty": 1, "category": "Écriture"},
            {"name": "Surligneur (lot de 4)", "qty": 1, "category": "Écriture"},
            {"name": "Correcteur (souris ou stylo)", "qty": 1, "category": "Écriture"},
            {"name": "Gomme blanche", "qty": 1, "category": "Écriture"},
            {"name": "Règle plate 30cm", "qty": 1, "category": "Traçage"},
            {"name": "Équerre 60°", "qty": 1, "category": "Traçage"},
            {"name": "Compas", "qty": 1, "category": "Traçage"},
            {"name": "Rapporteur", "qty": 1, "category": "Traçage"},
            {"name": "Boîte de crayons de couleur (12)", "qty": 1, "category": "Coloriage"},
            {"name": "Paire de ciseaux", "qty": 1, "category": "Découpage"},
            {"name": "Bâton de colle 21g", "qty": 2, "category": "Collage"},
            {"name": "Cahier 24x32 96 pages grands carreaux", "qty": 5, "category": "Cahier"},
            {"name": "Cahier 24x32 96 pages petits carreaux", "qty": 3, "category": "Cahier"},
            {"name": "Classeur A4 4 anneaux", "qty": 2, "category": "Classement"},
            {"name": "Lot de feuilles simples A4 grands carreaux", "qty": 3, "category": "Papier"},
            {"name": "Lot de feuilles doubles A4 grands carreaux", "qty": 2, "category": "Papier"},
            {"name": "Calculatrice collège scientifique", "qty": 1, "category": "Calcul"},
            {"name": "Clé USB 16Go", "qty": 1, "category": "Numérique"},
        ]
    },
    "2nde": {
        "level": "Seconde",
        "cycle": "Lycée",
        "items": [
            {"name": "Sac à dos lycée", "qty": 1, "category": "Maroquinerie"},
            {"name": "Trousse", "qty": 1, "category": "Maroquinerie"},
            {"name": "Agenda", "qty": 1, "category": "Organisation"},
            {"name": "Stylo bille bleu, noir, rouge, vert", "qty": 4, "category": "Écriture"},
            {"name": "Porte-mine 0.5mm + mines", "qty": 1, "category": "Écriture"},
            {"name": "Surligneur (lot de 4)", "qty": 1, "category": "Écriture"},
            {"name": "Correcteur (souris)", "qty": 1, "category": "Écriture"},
            {"name": "Gomme blanche", "qty": 1, "category": "Écriture"},
            {"name": "Règle plate 30cm", "qty": 1, "category": "Traçage"},
            {"name": "Équerre 60°", "qty": 1, "category": "Traçage"},
            {"name": "Compas", "qty": 1, "category": "Traçage"},
            {"name": "Rapporteur", "qty": 1, "category": "Traçage"},
            {"name": "Cahier 24x32 96 pages grands carreaux", "qty": 6, "category": "Cahier"},
            {"name": "Cahier 24x32 96 pages petits carreaux", "qty": 3, "category": "Cahier"},
            {"name": "Classeur A4 4 anneaux", "qty": 3, "category": "Classement"},
            {"name": "Lot de feuilles simples A4 grands carreaux", "qty": 3, "category": "Papier"},
            {"name": "Lot de feuilles doubles A4 grands carreaux", "qty": 2, "category": "Papier"},
            {"name": "Intercalaires 12 positions", "qty": 3, "category": "Classement"},
            {"name": "Pochettes plastiques perforées (lot 100)", "qty": 1, "category": "Classement"},
            {"name": "Calculatrice graphique lycée", "qty": 1, "category": "Calcul"},
            {"name": "Clé USB 32Go", "qty": 1, "category": "Numérique"},
        ]
    },
    "1ere": {
        "level": "Première",
        "cycle": "Lycée",
        "items": [
            {"name": "Sac à dos lycée", "qty": 1, "category": "Maroquinerie"},
            {"name": "Trousse", "qty": 1, "category": "Maroquinerie"},
            {"name": "Agenda", "qty": 1, "category": "Organisation"},
            {"name": "Stylo bille bleu, noir, rouge, vert", "qty": 4, "category": "Écriture"},
            {"name": "Porte-mine 0.5mm + mines", "qty": 1, "category": "Écriture"},
            {"name": "Surligneur (lot de 4)", "qty": 1, "category": "Écriture"},
            {"name": "Correcteur (souris)", "qty": 1, "category": "Écriture"},
            {"name": "Règle plate 30cm", "qty": 1, "category": "Traçage"},
            {"name": "Cahier 24x32 96 pages grands carreaux", "qty": 6, "category": "Cahier"},
            {"name": "Cahier 24x32 96 pages petits carreaux", "qty": 3, "category": "Cahier"},
            {"name": "Classeur A4 4 anneaux", "qty": 3, "category": "Classement"},
            {"name": "Lot de feuilles simples A4 grands carreaux", "qty": 3, "category": "Papier"},
            {"name": "Lot de feuilles doubles A4 grands carreaux", "qty": 2, "category": "Papier"},
            {"name": "Intercalaires 12 positions", "qty": 3, "category": "Classement"},
            {"name": "Pochettes plastiques perforées (lot 100)", "qty": 1, "category": "Classement"},
            {"name": "Calculatrice graphique lycée", "qty": 1, "category": "Calcul"},
            {"name": "Clé USB 32Go", "qty": 1, "category": "Numérique"},
        ]
    },
    "Terminale": {
        "level": "Terminale",
        "cycle": "Lycée",
        "items": [
            {"name": "Sac à dos lycée", "qty": 1, "category": "Maroquinerie"},
            {"name": "Trousse", "qty": 1, "category": "Maroquinerie"},
            {"name": "Agenda", "qty": 1, "category": "Organisation"},
            {"name": "Stylo bille bleu, noir, rouge, vert", "qty": 4, "category": "Écriture"},
            {"name": "Porte-mine 0.5mm + mines", "qty": 1, "category": "Écriture"},
            {"name": "Surligneur (lot de 4)", "qty": 1, "category": "Écriture"},
            {"name": "Correcteur (souris)", "qty": 1, "category": "Écriture"},
            {"name": "Règle plate 30cm", "qty": 1, "category": "Traçage"},
            {"name": "Cahier 24x32 96 pages grands carreaux", "qty": 5, "category": "Cahier"},
            {"name": "Cahier 24x32 96 pages petits carreaux", "qty": 3, "category": "Cahier"},
            {"name": "Classeur A4 4 anneaux", "qty": 3, "category": "Classement"},
            {"name": "Lot de feuilles simples A4 grands carreaux", "qty": 3, "category": "Papier"},
            {"name": "Lot de feuilles doubles A4 grands carreaux", "qty": 2, "category": "Papier"},
            {"name": "Intercalaires 12 positions", "qty": 3, "category": "Classement"},
            {"name": "Pochettes plastiques perforées (lot 100)", "qty": 1, "category": "Classement"},
            {"name": "Calculatrice graphique lycée", "qty": 1, "category": "Calcul"},
            {"name": "Clé USB 32Go", "qty": 1, "category": "Numérique"},
        ]
    },
}
