"""
Données des listes scolaires par niveau — ma-papeterie.fr
14 niveaux de la maternelle aux études supérieures.
"""

LISTES = {
    "maternelle": {
        "label": "Maternelle (PS/MS/GS)",
        "slug": "maternelle",
        "school_type": "maternelle",
        "essentiels": [
            "cahier 24x32 grands carreaux",
            "cahier de dessin 24x32",
            "crayons de couleur 12",
            "feutres coloriage 12",
            "colle bâton",
            "ciseaux bout rond",
            "ardoise effaçable",
            "protège-cahier 24x32",
        ]
    },
    "cp": {
        "label": "CP",
        "slug": "cp",
        "school_type": "élémentaire",
        "essentiels": [
            "cahier grands carreaux séyès 48 pages",
            "cahier petits carreaux 5x5",
            "cahier de brouillon",
            "crayon à papier HB",
            "gomme blanche",
            "taille-crayon avec réservoir",
            "crayons de couleur 12",
            "règle plate 20cm",
            "bâton de colle",
            "ciseaux 13cm",
            "trousse",
            "cahier de texte",
        ]
    },
    "ce1": {
        "label": "CE1",
        "slug": "ce1",
        "school_type": "élémentaire",
        "essentiels": [
            "cahier grands carreaux séyès 96 pages",
            "cahier petits carreaux 5x5 A4",
            "cahier de brouillon",
            "stylo bille bleu",
            "crayon à papier HB",
            "gomme blanche",
            "taille-crayon",
            "crayons de couleur 12",
            "règle 30cm",
            "bâton de colle",
            "ciseaux 17cm",
            "trousse",
            "cahier de texte",
        ]
    },
    "ce2": {
        "label": "CE2",
        "slug": "ce2",
        "school_type": "élémentaire",
        "essentiels": [
            "cahier grands carreaux séyès 96 pages",
            "cahier petits carreaux 5x5 A4",
            "classeur 4 anneaux A4",
            "intercalaires",
            "stylo bille bleu rouge",
            "crayon à papier",
            "gomme",
            "règle 30cm",
            "compas",
            "équerre",
            "rapporteur",
            "crayons de couleur",
            "trousse",
            "agenda scolaire",
        ]
    },
    "cm1": {
        "label": "CM1",
        "slug": "cm1",
        "school_type": "élémentaire",
        "essentiels": [
            "cahier grands carreaux séyès A4",
            "cahier petits carreaux A4",
            "classeur souple A4",
            "feuillets mobiles grands carreaux",
            "pochettes plastiques perforées",
            "stylos bille 4 couleurs",
            "porte-mine 0.5mm",
            "gomme",
            "règle 30cm",
            "compas",
            "équerre",
            "rapporteur",
            "surligneur",
            "trousse",
            "agenda scolaire",
        ]
    },
    "cm2": {
        "label": "CM2",
        "slug": "cm2",
        "school_type": "élémentaire",
        "essentiels": [
            "cahier grands carreaux séyès A4",
            "cahier petits carreaux A4",
            "classeur souple A4",
            "feuillets mobiles",
            "pochettes perforées",
            "stylos bille 4 couleurs",
            "porte-mine",
            "gomme",
            "règle 30cm",
            "compas",
            "équerre",
            "rapporteur",
            "calculatrice",
            "trousse",
            "agenda scolaire",
        ]
    },
    "6eme": {
        "label": "6ème",
        "slug": "6eme",
        "school_type": "collège",
        "essentiels": [
            "classeur à levier A4",
            "classeur souple A4",
            "cahier polypro A4 grands carreaux",
            "feuillets mobiles séyès A4",
            "feuillets mobiles petits carreaux A4",
            "pochettes perforées",
            "intercalaires 12 touches",
            "stylos bille 4 couleurs",
            "stylo plume",
            "cartouches encre",
            "porte-mine 0.5mm",
            "gomme",
            "règle 30cm",
            "compas",
            "équerre 60°",
            "rapporteur 180°",
            "calculatrice scientifique",
            "surligneur 3 couleurs",
            "trousse",
            "agenda scolaire",
        ]
    },
    "5eme": {
        "label": "5ème",
        "slug": "5eme",
        "school_type": "collège",
        "essentiels": [
            "classeurs à levier A4",
            "cahier polypro A4",
            "feuillets mobiles",
            "pochettes perforées",
            "stylos bille 4 couleurs",
            "stylo plume + cartouches",
            "porte-mine",
            "règle 30cm",
            "compas",
            "équerre",
            "rapporteur",
            "calculatrice scientifique",
            "surligneur",
            "trousse",
            "agenda scolaire",
        ]
    },
    "4eme": {
        "label": "4ème",
        "slug": "4eme",
        "school_type": "collège",
        "essentiels": [
            "classeurs A4",
            "cahiers polypro A4",
            "feuillets mobiles",
            "stylos bille 4 couleurs",
            "porte-mine 0.5mm",
            "calculatrice scientifique Casio fx-92",
            "surligneur",
            "trousse",
            "agenda scolaire",
        ]
    },
    "3eme": {
        "label": "3ème",
        "slug": "3eme",
        "school_type": "collège",
        "essentiels": [
            "classeurs A4",
            "cahiers polypro A4",
            "feuillets mobiles",
            "stylos bille 4 couleurs",
            "porte-mine",
            "calculatrice scientifique",
            "surligneur",
            "trousse",
            "agenda scolaire",
        ]
    },
    "seconde": {
        "label": "Seconde",
        "slug": "seconde",
        "school_type": "lycée",
        "essentiels": [
            "classeurs A4",
            "feuillets mobiles petits carreaux",
            "feuillets mobiles séyès",
            "cahier polypro A4",
            "stylos bille",
            "porte-mine 0.5mm",
            "calculatrice graphique",
            "surligneur 4 couleurs",
            "trousse",
            "agenda",
        ]
    },
    "premiere": {
        "label": "Première",
        "slug": "premiere",
        "school_type": "lycée",
        "essentiels": [
            "classeurs A4",
            "feuillets mobiles",
            "stylos bille",
            "porte-mine",
            "calculatrice graphique",
            "surligneur",
            "trousse",
            "agenda",
        ]
    },
    "terminale": {
        "label": "Terminale",
        "slug": "terminale",
        "school_type": "lycée",
        "essentiels": [
            "classeurs A4",
            "feuillets mobiles",
            "stylos bille",
            "porte-mine",
            "calculatrice graphique TI ou Casio",
            "surligneur",
            "trousse",
            "agenda",
        ]
    },
    "superieur": {
        "label": "Études supérieures",
        "slug": "superieur",
        "school_type": "supérieur",
        "essentiels": [
            "classeur A4",
            "cahier à spirales A4",
            "feuillets mobiles",
            "stylos bille",
            "porte-mine",
            "surligneur",
            "trousse",
            "agenda étudiant",
        ]
    },
}
