
-- Table for storing reorder suggestions generated by AI
CREATE TABLE public.reorder_suggestions (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  product_id UUID REFERENCES public.products(id),
  product_name TEXT NOT NULL,
  current_stock INTEGER DEFAULT 0,
  suggested_quantity INTEGER NOT NULL,
  urgency TEXT NOT NULL DEFAULT 'medium' CHECK (urgency IN ('low', 'medium', 'high')),
  best_supplier TEXT,
  estimated_cost NUMERIC(10,2),
  reasoning TEXT,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'ordered')),
  approved_by UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.reorder_suggestions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can manage reorder suggestions" ON public.reorder_suggestions
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role IN ('admin', 'super_admin'))
  );

CREATE TRIGGER update_reorder_suggestions_updated_at
  BEFORE UPDATE ON public.reorder_suggestions
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- Table for pricing opportunity insights from AI analysis
CREATE TABLE public.pricing_insights (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  product_id UUID REFERENCES public.products(id),
  insight_type TEXT NOT NULL CHECK (insight_type IN ('price_increase', 'price_decrease', 'margin_alert', 'competitor_gap', 'trend')),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  priority TEXT NOT NULL DEFAULT 'medium' CHECK (priority IN ('low', 'medium', 'high', 'critical')),
  suggested_price NUMERIC(10,2),
  current_price NUMERIC(10,2),
  potential_gain NUMERIC(10,2),
  competitor_data JSONB,
  status TEXT NOT NULL DEFAULT 'new' CHECK (status IN ('new', 'reviewed', 'applied', 'dismissed')),
  reviewed_by UUID,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.pricing_insights ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can manage pricing insights" ON public.pricing_insights
  FOR ALL USING (
    EXISTS (SELECT 1 FROM public.user_roles WHERE user_id = auth.uid() AND role IN ('admin', 'super_admin'))
  );
