// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import { createBrowserClient } from '@supabase/ssr';
import type { Database } from './types-extensions';
import { env } from '@/config/env';

const SUPABASE_URL = env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// SSR-safe: localStorage is not available during Astro prerendering
const isBrowser = typeof window !== 'undefined';

// @supabase/ssr stores browser sessions in cookies and uses PKCE by default,
// making the same validated session available to Astro middleware.
export const supabase = isBrowser
  ? createBrowserClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY)
  : createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false },
    });

/** Expose the URL for code that needs to build Edge Function URLs */
export const SUPABASE_PROJECT_URL = SUPABASE_URL;
